// <auto-generated />
using Apex.Events.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apex.Events.Data.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    partial class EventsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Apex.Events.Data.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            EventName = "Annual Conference"
                        },
                        new
                        {
                            EventId = 2,
                            EventName = "Networking Gala"
                        });
                });

            modelBuilder.Entity("Apex.Events.Data.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("GuestId");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            GuestId = 1,
                            Email = "",
                            FirstName = "Alice",
                            LastName = "Johnson"
                        },
                        new
                        {
                            GuestId = 2,
                            Email = "",
                            FirstName = "Bob",
                            LastName = "Smith"
                        },
                        new
                        {
                            GuestId = 3,
                            Email = "",
                            FirstName = "Charlie",
                            LastName = "Brown"
                        });
                });

            modelBuilder.Entity("Apex.Events.Data.GuestBooking", b =>
                {
                    b.Property<int>("GuestBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuestBookingId");

                    b.HasIndex("EventId");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestBookings");

                    b.HasData(
                        new
                        {
                            GuestBookingId = 1,
                            EventId = 1,
                            GuestId = 1
                        },
                        new
                        {
                            GuestBookingId = 2,
                            EventId = 1,
                            GuestId = 2
                        },
                        new
                        {
                            GuestBookingId = 3,
                            EventId = 2,
                            GuestId = 3
                        });
                });

            modelBuilder.Entity("Apex.Events.Data.Staff", b =>
                {
                    b.Property<int>("EventStaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EventStaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            EventStaffId = 1,
                            FirstName = "David",
                            LastName = "Wilson",
                            Role = "Coordinator"
                        },
                        new
                        {
                            EventStaffId = 2,
                            FirstName = "Eva",
                            LastName = "Davis",
                            Role = "Assistant"
                        });
                });

            modelBuilder.Entity("Apex.Events.Data.Staffing", b =>
                {
                    b.Property<int>("StaffingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StaffingName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("StaffingId");

                    b.HasIndex("EventId");

                    b.HasIndex("EventStaffId");

                    b.ToTable("Staffings");

                    b.HasData(
                        new
                        {
                            StaffingId = 1,
                            EventId = 1,
                            EventStaffId = 1,
                            StaffingName = "Conference Coordination"
                        },
                        new
                        {
                            StaffingId = 2,
                            EventId = 2,
                            EventStaffId = 2,
                            StaffingName = "Gala Assistance"
                        });
                });

            modelBuilder.Entity("Apex.Events.Data.GuestBooking", b =>
                {
                    b.HasOne("Apex.Events.Data.Event", "Event")
                        .WithMany("GuestBookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apex.Events.Data.Guest", "Guest")
                        .WithMany("GuestBookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Apex.Events.Data.Staffing", b =>
                {
                    b.HasOne("Apex.Events.Data.Event", "Event")
                        .WithMany("Staffings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apex.Events.Data.Staff", "Staff")
                        .WithMany("Staffings")
                        .HasForeignKey("EventStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Apex.Events.Data.Event", b =>
                {
                    b.Navigation("GuestBookings");

                    b.Navigation("Staffings");
                });

            modelBuilder.Entity("Apex.Events.Data.Guest", b =>
                {
                    b.Navigation("GuestBookings");
                });

            modelBuilder.Entity("Apex.Events.Data.Staff", b =>
                {
                    b.Navigation("Staffings");
                });
#pragma warning restore 612, 618
        }
    }
}
