// <auto-generated />
using Apex.Catering.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apex.Catering.Data.Migrations
{
    [DbContext(typeof(CateringDbContext))]
    [Migration("20251106124347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Apex.Catering.Data.FoodBooking", b =>
                {
                    b.Property<int>("FoodBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodBookingId");

                    b.HasIndex("MenuId");

                    b.ToTable("FoodBookings");

                    b.HasData(
                        new
                        {
                            FoodBookingId = 1,
                            ClientReferenceId = 1001,
                            MenuId = 1,
                            NumberOfGuests = 50
                        },
                        new
                        {
                            FoodBookingId = 2,
                            ClientReferenceId = 1002,
                            MenuId = 2,
                            NumberOfGuests = 100
                        },
                        new
                        {
                            FoodBookingId = 3,
                            ClientReferenceId = 1003,
                            MenuId = 3,
                            NumberOfGuests = 200
                        });
                });

            modelBuilder.Entity("Apex.Catering.Data.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            Description = "Chicken Sandwich",
                            UnitPrice = 5.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 2,
                            Description = "Veggie Wrap",
                            UnitPrice = 4.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 3,
                            Description = "Caesar Salad",
                            UnitPrice = 3.9900000000000002
                        });
                });

            modelBuilder.Entity("Apex.Catering.Data.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuName = "Conference Menu"
                        },
                        new
                        {
                            MenuId = 2,
                            MenuName = "Party Menu"
                        },
                        new
                        {
                            MenuId = 3,
                            MenuName = "Wedding Menu"
                        });
                });

            modelBuilder.Entity("Apex.Catering.Data.MenuFoodItem", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuId", "FoodItemId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("MenuFoodItems");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 3
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 1
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 2
                        });
                });

            modelBuilder.Entity("Apex.Catering.Data.FoodBooking", b =>
                {
                    b.HasOne("Apex.Catering.Data.Menu", "Menu")
                        .WithMany("FoodBookings")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Apex.Catering.Data.MenuFoodItem", b =>
                {
                    b.HasOne("Apex.Catering.Data.FoodItem", null)
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Apex.Catering.Data.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Apex.Catering.Data.Menu", b =>
                {
                    b.Navigation("FoodBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
